data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5432/data-base-1
    table: users
    user: testuser
    password: testpass
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
